"""add audit columns

Revision ID: 425f3ff1fe5d
Revises: eacb4a6d13e8
Create Date: 2025-12-10 19:40:53.641298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '425f3ff1fe5d'
down_revision: Union[str, Sequence[str], None] = 'eacb4a6d13e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('appointments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('appointments', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('appointments_patient_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'patients', ['patient_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('patients', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('patients', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('patients', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'is_deleted')
    op.drop_column('patients', 'updated_at')
    op.drop_column('patients', 'created_at')
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_patient_id_fkey'), 'appointments', 'patients', ['patient_id'], ['id'])
    op.drop_column('appointments', 'is_deleted')
    op.drop_column('appointments', 'updated_at')
    op.drop_column('appointments', 'created_at')
    # ### end Alembic commands ###
