"""add department and complaint to appointments

Revision ID: 60cd680543ab
Revises: ee1763daf2e3
Create Date: 2025-12-23 21:57:01.118749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60cd680543ab'
down_revision: Union[str, Sequence[str], None] = 'ee1763daf2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('department', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('complaint', sa.Text(), nullable=True))
    op.drop_constraint(op.f('appointments_doctor_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_patient_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'users', ['doctor_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'appointments', 'patients', ['patient_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_patient_id_fkey'), 'appointments', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(op.f('appointments_doctor_id_fkey'), 'appointments', 'users', ['doctor_id'], ['id'])
    op.drop_column('appointments', 'complaint')
    op.drop_column('appointments', 'department')
    # ### end Alembic commands ###
